### ISSUE TITLE
RuntimeError in test/example.py

### ISSUE THREAD

**Issue by bgshin** [salesforce/cove#3]
Thank you for your great work and providing the source code.

I tried to get it run, but I've got the following error message.
I'm wondering if there is anything that I need to do (I just followed the instruction)

```bash
Generating train, dev, test splits
Building vocabulary
loading word vectors from /home/bgshin/works/cove/glove.840B.300d.pt
Generating CoVe
Traceback (most recent call last):
  File "test/example.py", line 29, in <module>
    cove_premise = model(*batch.premise)
  File "/home/bgshin/.virtualenvs/cove/lib/python3.5/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/bgshin/works/cove/cove/encoder.py", line 50, in forward
    inputs = self.vectors(inputs.t()).t()
  File "/home/bgshin/.virtualenvs/cove/lib/python3.5/site-packages/torch/autograd/variable.py", line 729, in t
    raise RuntimeError("t() expects a 2D Variable, but self is {}D".format(self.dim()))
RuntimeError: t() expects a 2D Variable, but self is 3D
```

**Comment by bgshin** [comment]
In https://github.com/salesforce/cove/blob/master/cove/encoder.py#L49,
The following change fixed the error.

```python
    # inputs = self.vectors(inputs.t()).t()
    inputs = self.vectors(inputs)
```

**Comment by bmccann** [comment]
71834aac31348c09cb7ee9e39e64df0318988225
